ALTER TABLE expenses 
    ADD COLUMN created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN creator VARCHAR(250) DEFAULT NULL,
    ADD COLUMN modifier VARCHAR(250) DEFAULT NULL,
    ADD COLUMN creator_id INT NOT NULL,
    ADD COLUMN modifier_id INT NOT NULL; 

ALTER TABLE categories 
    ADD COLUMN created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN creator VARCHAR(250) DEFAULT NULL,
    ADD COLUMN modifier VARCHAR(250) DEFAULT NULL,
    ADD COLUMN creator_id INT NOT NULL,
    ADD COLUMN modifier_id INT NOT NULL;

ALTER TABLE currency 
    ADD COLUMN created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN creator VARCHAR(250) DEFAULT NULL,
    ADD COLUMN modifier VARCHAR(250) DEFAULT NULL,
    ADD COLUMN creator_id INT NOT NULL,
    ADD COLUMN modifier_id INT NOT NULL;

CREATE TABLE IF NOT EXISTS category_details (
    id SERIAL PRIMARY KEY,
    category_code VARCHAR(25) NOT NULL,
    types VARCHAR(50) NOT NULL,
    category_name VARCHAR(200) NOT NULL,
    is_parent_category BOOLEAN DEFAULT FALSE,
    is_custom_category BOOLEAN DEFAULT FALSE,  
    sub_category_codes TEXT[] DEFAULT NULL, 
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    creator VARCHAR(250) DEFAULT NULL,
    modifier VARCHAR(250) DEFAULT NULL,
    creator_id INT NOT NULL,
    modifier_id INT NOT NULL
);

ALTER TABLE category_details ALTER COLUMN types SET DATA TYPE smallint USING types::smallint;

